### ISSUE TITLE
[IL] Website not updating

### ISSUE THREAD

**Issue by aaronta** [thehackerwithin/illinois#4]
Hey @katyhuff & @gonuke,

I'm trying to update the Illinois website (http://thehackerwithin.github.io/illinois/) but Github doesn't seem to respond to all new merges (it got the first one but not any new ones). I ran a jekyll server on my local machine and cleaned up a couple configurations (_config.yml) errors but it didn't fix the website.  

Some googling said it should update ~10 min and an email will be sent with any errors with building the website, neither seem to be true. My email might not be sent the errors.

Is this normal and there something I'm not doing?

Thanks!
Aaron

**Comment by katyhuff** [comment]
From your description, I can't tell where the breakdown is happening.
1) are you successfully committing locally?
2) are you pushing the changes up successfully (the last one I see is from
an hour ago in config.)
3) in general, it will be easier to know what's gone wrong if you tell me
what's gone on. That is, What is the output of the history command? what
are you expecting to see? What's happening instead? Are you getting an
error or just failing to see the impacts of your change to the config file?

**Comment by gonuke** [comment]
I think you are pushing the wrong files to the `gh-pages` branch.

The contents of the `_site` subdirectory are the results of the rendering by Jekyll which GH does live and on-the-fly.

You need to push changes to the file `index.md` and not the `_site` directory.  The `_site` directory will be generated by GH pages.

**Comment by katyhuff** [comment]
yep. What paul said.

On Tue, Aug 4, 2015 at 9:03 AM, Paul Wilson <notifications@github.com>
wrote:

> I think you are pushing the wrong files to the gh-pages branch.
>
> The contents of the _site subdirectory are the results of the rendering
> by Jekyll which GH does live and on-the-fly.
>
> You need to push changes to the file index.md and not the _site
> directory. The _site directory will be generated by GH pages.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thehackerwithin/illinois/issues/4#issuecomment-127659658>
> .
>



-- 
http://katyhuff.github.com

**Comment by aaronta** [comment]
Ah! Thanks!

**Comment by gonuke** [comment]
To be clean - you may want to remove the `_site` directory, as well.
